info:
  component: A sandbox for playing with mapstruct in a microservice

spring:
#  main:
#    banner-mode: "off"
#  profiles:
#    active: local
  application:
    name: bordcomputer-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
    time-zone: UTC
  jpa:
    show-sql: true

server:
  port: 8080